### ISSUE TITLE
Seperate the CSS and JavaScript to diferent files

### ISSUE THREAD

**Issue by ReduxFlakes** [Leone25/pdf-labeler#2]
I think the title says all, I recommend you to move both CSS and JavaScript code to different files in a tree style
Example:
```
index.html
style.css
script.js
```
Like this, is much better to update and overall read the code of the website, I can do it but I want to know your opinion, overall a great tool, specially to organize my books, have a nice day!
_reduxflakes_

**Comment by Leone25** [comment]
hello, thank you for your feedback

I have deliberately decided to not separate the files as this is a small project and putting everything together makes it faster to load
